### ISSUE TITLE
Incompatibel due to wrong value in register? 

### ISSUE THREAD

**Issue by hmersch** [theknut/ioBroker.waterkotte-easycon#56]
I am running 0.0.3 from Github here. 
While connecting adapter stays at yellow and I get the error below. 

Is my heatpump incompatibel? Could we have more diagnostics? 

BR - Henning
```
waterkotte-easycon.0 | 2024-10-26 23:22:01.758 | error | Callstack: Error: Received invalid value '2' for id 'I138' at WaterkotteEasycon.updateParametersAsync (/opt/iobroker/node_modules/iobroker.waterkotte-easycon/build/main.js:192:25) at async WaterkotteEasycon.onReady (/opt/iobroker/node_modules/iobroker.waterkotte-easycon/build/main.js:53:24)
-- | -- | -- | --
waterkotte-easycon.0 | 2024-10-26 23:22:01.757 | error | Unhandled error on adapter startup: Error: Received invalid value '2' for id 'I138'
waterkotte-easycon.0 | 2024-10-26 23:22:01.738 | warn | Received invalid value '2' for id 'I138'

```

**Comment by hmersch** [comment]
There is a Modbus TCP at my Heatpump interface built-in which works quite good - clsing this
